name: task_Management
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+6

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^6.2.1
  permission_handler: ^11.3.1
  google_nav_bar: ^5.0.6
  flutter_animate: ^4.5.0
  path: ^1.9.0
  provider: ^6.1.2
  lottie: ^3.1.2
  awesome_notifications: ^0.9.3+1
  awesome_snackbar_content: ^0.1.4
  clipboard: ^0.1.3
  wakelock_plus: ^1.2.8
  shared_preferences: ^2.3.2
  google_mobile_ads: ^5.1.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.3
  stop_watch_timer: ^3.2.1
  toastification: ^3.0.3
  flutter_local_notifications: ^19.5.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: fontello
      fonts:
        - asset: assets/fonts/my_icons.ttf